//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSurveyCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSurveyTable
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Drivinglicense { get; set; }
        public string Firstcar { get; set; }
        public string Drivetrain { get; set; }
        public string Fuelemissions { get; set; }
        public Nullable<int> NoOfCar { get; set; }
        public string CarName { get; set; }
        public string CarModel { get; set; }
    }
}
